Bump dependencies to dioxus 0.6.
dioxus-community/dioxus-lazy pull request #7
Opened 2024-12-15 09:44 UTC by Emm

2024-12-15 10:12 UTC, marc2332 requested changes

2024-12-15 10:12 UTC, marc2332 commented on Cargo.toml
Any reason you use git links on this one? Rust crates can't be released with git dependencies

2024-12-15 10:14 UTC, marc2332 commented on Cargo.toml
>  dioxus-logger = "0.5.0"
Could you also update this one to 0.6.0?

2024-12-15 10:18 UTC, Emm commented
Sorry, I had forgotten to git push -f, should have re-read before opening
the PR

On Sun, 15 Dec 2024 at 11:15, Marc Espin ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Cargo.toml
> <https://github.com/dioxus-community/dioxus-lazy/pull/7#discussion_r1885634837>
> :
>
> >  edition = "2021"
>  license = "MIT OR Apache-2.0"
>  description = "Async list components for Dioxus"
>  repository = "https://github.com/dioxus-community/dioxus-lazy"
>
>  [dependencies]
> -dioxus = { version = "0.6.0-alpha.3", features = ["web"] }
> -dioxus-resize-observer = "0.3.0-alpha.4"
> -dioxus-use-mounted = "0.3.0-alpha.4"
> +dioxus = { version = "0.6.0", features = ["web"] }
> +dioxus-resize-observer = { git = "https://github.com/Emm/dioxus-resize-observer.git" }
> +dioxus-use-mounted = { git = "https://github.com/dioxus-community/dioxus-use-mounted" }
>  log = "0.4.22"
>  dioxus-logger = "0.5.0"
>
> Could you also update this one to 0.6.0?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dioxus-community/dioxus-lazy/pull/7#pullrequestreview-2504494297>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAID4M7XVHR6DLJZMYRWIT2FVJDNAVCNFSM6AAAAABTUMGH2KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBUGQ4TIMRZG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-15 22:03 UTC, marc2332 commented on Cargo.toml
>  dioxus-logger = "0.5.0"
Not sure if you misses this so here goes this comment :)

2024-12-16 07:36 UTC, Emm commented on Cargo.toml
By mistake :)

2024-12-16 13:31 UTC, marc2332 approved these changes

2024-12-16 13:31 UTC, merged

2024-12-16 13:33 UTC, marc2332 commented
Thanks!!

2024-12-16 14:17 UTC, Emm commented
Thanks for being so responsive :)

On Mon, 16 Dec 2024 at 14:34, Marc Espin ***@***.***> wrote:

> Thanks!!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dioxus-community/dioxus-lazy/pull/7#issuecomment-2545646967>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAID4LLSBFWDQ6CAQT7VRT2F3JERAVCNFSM6AAAAABTUMGH2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBVGY2DMOJWG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>